### ISSUE TITLE
Cannot open /var/www

### ISSUE THREAD

**Issue by WatchfulFox** [wanadev/yoga#42]
Just installed Yoga and I cannot browse /var/www to open files in my local web dev directories. Is there a way for me to let Yoga see these directories? I have tried via 'Other locations' with no success.

**Comment by flozz** [comment]
Hello,

I think you are posting in the wrong repository. This repository is **YOGA**, the Python library and CLI tool to convert and optimize images and 3D models. I think your issue is related to [**YOGA Image Optimizer**](https://github.com/flozz/yoga-image-optimizer/), the GTK GUI for the image part of YOGA (yeah I know it is a bit confusing...).

Anyway, if you installed YOGA Image Optimizer from Flathub, there is some known limitations due to the Flatpak sandbox. Folder such as `/tmp` and `/var` are not accessible to the application. For more information, please read the following issue:

https://github.com/flozz/yoga-image-optimizer/issues/18

:)

**Comment by WatchfulFox** [comment]
Thanks flozz,

Actually, you are right :)  And.. I just solved the problem. It was a folder permissions issue. Thanks for taking the time to read the question. Feel free to delete this thread if it messes up your otherwise tidy Issues area!! I'll see myself out...
